# Lab 1 - Vectors and Matrices
This notebook demonstrates the use of vectors and matrices in IPython. Note that the basis is not explicit in any of these operations. You must keep track of the basis yourself (using variable names, or notes etc).

In [8]:
from numpy import array, dot, outer, sqrt, matrix
from numpy.linalg import eig, eigvals
from matplotlib.pyplot import hist

In [9]:
%matplotlib inline

In [3]:
rv = array([1,2])  # a row vector
rv

array([1, 2])

In [4]:
cv = array([[3],[4]])  # a column vector
cv

array([[3],
       [4]])

Two kinds of vector products we'll see: inner product (dot product) and outer product

### 1) Use the function _dot(vector1, vector2)_ to find the dot product of rv and cv. Does the order of the arguments matter?

In [5]:
dot(rv,cv)

array([11])

In [6]:
dot(cv,rv)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

### 2) Use the function _outer(vector1, vector2)_ to find the outer product of rv and cv. Does the order of the arguments matter?

In [ ]:
outer(rv,cv)

In [ ]:
outer(cv,rv)

## II. Complex vectors

In [ ]:
# Complex numbers in python have a j term:
a = 1+2j

In [ ]:
v1 = array([1+2j, 3+2j, 5+1j, 4+0j])

The complex conjugate changes the sign of the imaginary part:

In [ ]:
v1.conjugate()

### 3) Use _dot()_ and _.conjugate()_ to find the dot product of v1 and it's own conjugate:

In [ ]:
dot(v1.conjugate(),v1)

## III. Matrices

In [ ]:
# a two-dimensional array
m1 = array([[2,1],[2,1]])
m1

In [ ]:
# can find transpose with the T method:
m1.T

In [ ]:
# find the eigenvalues and eigenvectors of a matrix:
eig(m1)

Can also use the `matrix` type which is like array but restricts to 2D. Also, `matrix` adds `.H` and `.I` methods for hermitian and inverse, respectively. For more information, see Stack Overflow question [#4151128](http://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u)

In [ ]:
m2 = matrix( [[2,1],[2,1]])

In [ ]:
m2.H

In [ ]:
eig(m2)

In [ ]:
# use a question mark to get help on a command
eig?

# Examples:
## Example 1.4
Find the eigenvalues and eigenvectors of M = ([0,1],[-2,3]])

In [ ]:
M14 = array([[0,1],[-2,3]])

In [ ]:
eig(M14)

Interpret this result:
the two eigenvalues are 1 and 2
the eigenvectors are strange decimals, but we can check them against the stated solution:

In [ ]:
1/sqrt(2)  # this is the value for both entries in the first eigenvector

In [ ]:
1/sqrt(5)  # this is the first value in the second eigenvector

In [ ]:
2/sqrt(5)  # this is the second value in the second eigenvector

In [ ]:
eigvals(M14)

Signs are opposite compared to the book, but it turns out that (-) doesn't matter in the interpretation of eigenvectors: only "direction" matters (the relative size of the entries).

## Example: Problem 1.16 using Ipython functions

In [ ]:
M16 = array([[0,-1j],[1j,0]])

In [ ]:
evals, evecs = eig(M16)

In [ ]:
evecs

In [ ]:
evecs[:,0]

In [ ]:
evecs[:,1]

In [ ]:
dot(evecs[:,0].conjugate(),evecs[:,1])

# Part 2: Using QuTiP
Keeping track of row and column vectors in Ipython is somewhat artificial and tedious. The QuTiP library is designed to take care of many of these headaches

In [ ]:
from qutip import *

In [7]:
# Create a row vector:
qv = Qobj([[1,2]])
qv

NameError: name 'Qobj' is not defined

In [ ]:
# Find the corresponding column vector
qv.dag()

In [ ]:
qv2 = Qobj([[1+2j,4-1j]])
qv2

In [ ]:
qv2.dag()

## Vector products in QuTiP
Only need to know one operator: "\*"
The product will depend on the order, either inner or outer

In [ ]:
qv2*qv2.dag()  # inner product (dot product)

In [ ]:
qv2.dag()*qv2  # outer product

## Matrix in QuTiP

In [ ]:
qm = Qobj([[1,2],[2,1]])
qm

In [ ]:
qm.eigenenergies()  # in quantum (as we will learn) eigenvalues often correspond to energy levels

In [ ]:
evals, evecs = qm.eigenstates()

In [ ]:
evecs

In [ ]:
evecs[0]

# Practice:

## Problem 1.2 using the _hist()_ function.

In [ ]:
# Solution goes here

In [ ]:
# Solution goes here

In [ ]:
# Solution goes here

## Problem 1.8
**Hint:** using sympy, we can calculate the relevant integral. The conds='none' asks the solver to ignore any strange conditions on the variables in the integral. This is fine for most of our integrals. Usually the variables are real and well-behaved numbers.

In [ ]:
# Solution goes here