# Minilab 1 - Jones Calculus
This notebook demonstrates the use the Jones calculus and provides you with additional practice in IPython.

## Using QuTiP
In order to move smoothly into the quantum mechanics of Chapter 3, we'll use QuTiP as our vector and matrix library from this point forward through the rest of the course.

In [1]:
from qutip import *

In [7]:
# Create a row vector:
rv = Qobj([[1,2]])
rv

Quantum object: dims = [[1], [2]], shape = [1, 2], type = bra
Qobj data =
[[ 1.  2.]]

In [8]:
# Find the corresponding column vector
rv.dag()

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 1.]
 [ 2.]]

In [9]:
# Create a column vector:
cv = Qobj([[1],[4]])
cv

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 1.]
 [ 4.]]

In [10]:
# Convert to a row vector:
cv.dag()

Quantum object: dims = [[1], [2]], shape = [1, 2], type = bra
Qobj data =
[[ 1.  4.]]

## Review: Vector products in QuTiP
Only need to know one operator: "\*"
The product will depend on the order, either inner or outer

In [11]:
rv*cv  # inner product (dot product)

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 9.]]

In [12]:
rv*rv.dag()  # dot product with itself, need row vector first

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 5.]]

In [14]:
rv.norm() # find the length of the vector

2.23606797749979

In [4]:
# verify that the norm of the vector is the square root of the dot product with itself:
from numpy import sqrt
sqrt(5)

2.2360679774997898

## Review: Matrix in QuTiP

In [19]:
qm = Qobj([[1,2],[2,1]])
qm

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  2.]
 [ 2.  1.]]

In [20]:
qm.eigenenergies()  # in quantum (as we will learn) eigenvalues often correspond to energy levels

array([-1.,  3.])

In [21]:
evals, evecs = qm.eigenstates()

In [22]:
evecs

array([ Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]],
       Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.70710678]
 [ 0.70710678]]], dtype=object)

In [23]:
# Select the first eigenvector using an index inside square brackets:
# Index counting starts at zero so [0] picks the first one:
evecs[0]

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[-0.70710678]
 [ 0.70710678]]

# Activity for Lab:
In order to solve the following problems, make use of these definitions for the various states of polarization and matrices for different devices:

In [5]:
# States:
horiz = Qobj([[1],[0]])
vert = Qobj([[0],[1]])
p45 = 1/sqrt(2)*Qobj([[1],[1]])
m45 = 1/sqrt(2)*Qobj([[1],[-1]])
lcp = 1/sqrt(2)*Qobj([[1],[1j]])
rcp = 1/sqrt(2)*Qobj([[1],[-1j]])

# Operators:
HP = Qobj([[1,0],[0,0]])
VP = Qobj([[0,0],[0,1]])
qwp_p45 = 1/sqrt(2)*Qobj([[1,-1j],[-1j,1]])
qwp_m45 = 1/sqrt(2)*Qobj([[1,1j],[1j,1]])

In [39]:
# To display one of these, simply put it at the end of a cell:
HP

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  0.]]

In [40]:
# An example calculation, the state of light after +45 polarization goes through a horizontal polarizer:
HP*p45

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]]

In [9]:
V = qwp_p45*horiz
V

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.70710678+0.j        ]
 [ 0.00000000-0.70710678j]]

## Problem 2.2

In [1]:
from numpy import *

In [46]:
#a)

H= Qobj([[cos(deg2rad(45)), sin(deg2rad(45))], [sin(deg2rad(45)), -cos(deg2rad(45))]])
Q= Qobj([[cos(deg2rad(90))**2+1j*sin(deg2rad(90))**2, (1-1j)*sin(deg2rad(90))*cos(deg2rad(90))],
   [(1-1j)*sin(deg2rad(90))*cos(deg2rad(90)), sin(deg2rad(90))**2+1j*cos(deg2rad(90))**2]])


M=qwp_m45*Q*H
M

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = False
Qobj data =
[[ 0.+1.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]

In [47]:
#b)
B = M * horiz
B

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.+1.j]
 [ 0.+0.j]]

## Problem 2.4

In [35]:
N = H * rcp

N

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.5-0.5j]
 [ 0.5+0.5j]]

## Problem 2.10

In [54]:
#a)
P = qwp_m45 * HP * qwp_p45

P

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.5+0.j   0.0-0.5j]
 [ 0.0+0.5j  0.5+0.j ]]

In [55]:
#b)
W = P * rcp
E = B.dag() * W * B.norm() **2
W
E

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.]]

In [53]:
#C
R = P * rcp
T = B.dag() * W * B.norm() **2
R
T

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.]]

## Problem 2.11

In [48]:
#a
C = qwp_m45 * VP * qwp_p45

C

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.5+0.j   0.0+0.5j]
 [ 0.0-0.5j  0.5+0.j ]]

In [58]:
#b
u = C * rcp
y = B.dag() * B.norm() **2
y

0.9999999999999998

In [57]:
#c
I = C * rcp
O = B.dag() * u * B.norm() **2
O

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = False
Qobj data =
[[ 0.-0.70710678j]]