In [34]:
from numpy import array, dot, outer, sqrt, matrix
from numpy.linalg import eig, eigvals
from matplotlib.pyplot import hist

In [17]:
#4.3
# |psi> = Ch|H>+Cv|V>
# |Ph|psi> = Ch|H>

# <psi|Ph = <H|Ch.dag()+<V|Cv.dag() * |H><H|
# = 1

In [18]:
H = Qobj([[1],[0]])
V = Qobj([[0],[1]])

(H*H.dag()+V*V.dag())*(H*H.dag())

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  0.]]

In [19]:
#4.4
def Rp(theta):
    return Qobj([[cos(theta),-sin(theta)],[sin(theta),cos(theta)]]).tidyup()

Rp(pi/2).dag()*Rp(pi/2)
#identity matrix shown

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  1.]]

In [20]:
#4.14
P45 = Qobj([[1/sqrt(2)],[1/sqrt(2)]])
J = P45.dag()*P45

J.eigenstates()
#this makes sense. It is equivalent to <H|V> which we know is 1

(array([ 1.]),
 array([ Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
 Qobj data =
 [[ 1.]]], dtype=object))

In [21]:
#4.15

M = Rp(pi/2)

M.eigenstates()

(array([  0.00000000e+00+1.j,   2.77555756e-17-1.j]),
 array([ Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
 Qobj data =
 [[ 0.70710678+0.j        ]
  [ 0.00000000-0.70710678j]],
        Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
 Qobj data =
 [[ 0.70710678+0.j        ]
  [ 0.00000000+0.70710678j]]], dtype=object))

In [38]:
#4.19

Phv = H*H.dag() - V*V.dag()
Phv

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [40]:
Phv = ([1,0],[0,-1])
lamda = eigvals(Phv)
lamda

array([ 1., -1.])

In [41]:
(exp(Phv))*lamda

array([[ 2.71828183, -1.        ],
       [ 1.        , -0.36787944]])