In [6]:
from pylab import *
%matplotlib inline
from numpy import *
from qutip import *

In [13]:
#2.3
#a)
M = Qobj([[cos(pi/4)**2, cos(pi/4)*sin(pi/4)], [cos(pi/4)*sin(pi/4), sin(pi/4)**2]])

M

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.5  0.5]
 [ 0.5  0.5]]

In [16]:
M.eigenstates()

(array([ 0.,  1.]),
 array([ Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
 Qobj data =
 [[ 0.70710678]
  [-0.70710678]],
        Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
 Qobj data =
 [[-0.70710678]
  [-0.70710678]]], dtype=object))

In [17]:
#b)
#1/root(2)(1,-1) is a -45degree polarized light  (0) means no light would get through
#-1/root(2)(1,1) is a 45degree polarized light  (1) means all light gets through

In [24]:
#2.6
phi = 1
J = Qobj([[exp(1j)*phi, 0], [0, 1]])

J

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = False
Qobj data =
[[ 0.54030231+0.84147098j  0.00000000+0.j        ]
 [ 0.00000000+0.j          1.00000000+0.j        ]]

In [25]:
J.eigenstates

<bound method Qobj.eigenstates of Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = False
Qobj data =
[[ 0.54030231+0.84147098j  0.00000000+0.j        ]
 [ 0.00000000+0.j          1.00000000+0.j        ]]>

In [29]:
h = Qobj([[1],[0]])

h

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 1.]
 [ 0.]]

In [30]:
v = Qobj([[0],[1]])

v

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.]
 [ 1.]]

In [31]:
J*h

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.54030231+0.84147098j]
 [ 0.00000000+0.j        ]]

In [32]:
J*v

Quantum object: dims = [[2], [1]], shape = [2, 1], type = ket
Qobj data =
[[ 0.]
 [ 1.]]